// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJuFyTE4_bMt7o-uXjLrgF96ZR1qVKGww',
    appId: '1:750046757369:android:f63f090009102fa476bd28',
    messagingSenderId: '750046757369',
    projectId: 'taskify-e4ca5',
    storageBucket: 'taskify-e4ca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-hJzhUdKEiNQRFjzKARMVg2qoa3Irmi4',
    appId: '1:750046757369:ios:75aa8524572e005976bd28',
    messagingSenderId: '750046757369',
    projectId: 'taskify-e4ca5',
    storageBucket: 'taskify-e4ca5.appspot.com',
    iosClientId: '750046757369-6q3clb8ashbr4tf8p36f6ribfmmkpqer.apps.googleusercontent.com',
    iosBundleId: 'com.cracklog.faay',
  );
}
